version: '3.9'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: proactive_job_analyzer
      MYSQL_USER: proactive_job_analyzer
      MYSQL_PASSWORD: ${MYSQL_PROACTIVE_JOB_ANALYZER_PASSWORD}
    volumes:
      - "${VOLUME_BASE}/mysql:/var/lib/mysql"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u proactive_job_analyzer --password=$$MYSQL_PROACTIVE_JOB_ANALYZER_PASSWORD

  webserver:
    image: secure-dl/job-analyzer-webservice:${SDL_JOB_ANALYZER_VERSION}
    restart: unless-stopped
    ports:
      - "127.0.0.1:${SDL_JOB_ANALYZER_PORT}:8080"

    environment:
      -SPRING_APPLICATION_JSON: '{
                "spring.datasource.url": "jdbc:mysql://db:3306/proactive_job_analyzer",
                "spring.datasource.username": "proactive_job_analyzer",
                "spring.datasource.password": "${MYSQL_PROACTIVE_JOB_ANALYZER_PASSWORD}",
                "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
                "spring.jpa.hibernate.ddl-auto": "validate",
                "spring.jpa.show-sql": true,
                "secure-dl.job-analyzer.compiler-classpath": "/sdl/analysis-runtime/*"
              }'
    depends_on:
      db:
        condition: service_healthy
